In [1]:
import torch

`requires_grad = True` it starts tracking all its operations

In [3]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

`y` was created as a result of an operation, so it has a `grad_fn`.

In [5]:
y.grad_fn

In [6]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


# Gradients

In [8]:
out.backward()

Performing d(out)/dx

In [9]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

We can stop autograd by enclosing the operations in `with torch.no_grad():`