In [1]:
import torch

# Tensors

In [2]:
# uninitialized matrix 
x = torch.empty(2,2)
x

tensor([[ 0.0000e+00, -3.6893e+19],
        [ 0.0000e+00, -3.6893e+19]])

In [4]:
# random matrix
x = torch.rand(2,2)
x

tensor([[0.0968, 0.1788],
        [0.7388, 0.8749]])

In [6]:
# zero matrix
z = torch.zeros(2,2, dtype=torch.long)
z

tensor([[0, 0],
        [0, 0]])

In [10]:
# tensor with data
t = torch.tensor([5.2,3])
u = torch.tensor([5,3])
print(t)
print(u)

tensor([5.2000, 3.0000])
tensor([5, 3])


In [14]:
t.size()

torch.Size([2])

# Operators

In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x+y

tensor([[1.0916, 0.5803],
        [0.7572, 1.4399]])

In [16]:
# or
torch.add(x,y)

tensor([[1.0916, 0.5803],
        [0.7572, 1.4399]])

In [20]:
result = torch.empty(2, 2)
torch.add(x,y, out=result)
result

tensor([[1.0916, 0.5803],
        [0.7572, 1.4399]])

In [22]:
# y = x+ y 
y.add_(x)
y

tensor([[1.4803, 0.6352],
        [0.8407, 2.2991]])

In [25]:
# Reshaping 
x = torch.rand(3,4)
y = x.view(12)
z = x.view(-1,6)
print(x.shape)
print(y.shape)
print(z.shape)


torch.Size([3, 4])
torch.Size([12])
torch.Size([2, 6])


In [30]:
# Convert to python scalars
x = torch.tensor([1.1])
num = x.item()
print(num)
print(x)

1.100000023841858
tensor([1.1000])


# Numpy <=> Tensor

In [32]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [33]:
y = x.numpy()
y

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [36]:
x.add_(1)
print(x)
print(y)

tensor([[3., 3.],
        [3., 3.]])
[[3. 3.]
 [3. 3.]]


In [37]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
