## Simple Neural Network using tensors

In [2]:
import torch

In [3]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [6]:
# generating data
torch.manual_seed(2)

# tensor of 5 normal variables: 1 row 5 columns
features = torch.randn((1,5))

# matrix which is same as the shape of features
weights = torch.randn_like(features)

# bias term
bias = torch.randn((1,1))

In [8]:
# output

y = activation(torch.sum(features * weights)+bias)

print(y)

tensor([[0.5380]])


In [17]:
# output using matrix multipication

weights = weights.view(5,1)

y1 = activation(torch.mm(features, weights) + bias)

print(y1)

tensor([[0.5380]])


## Multi Layer Network

In [30]:
torch.manual_seed(2) 

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Size of each layer
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)

# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [31]:
h = activation(torch.mm(features, W1)+B1)
y = activation(torch.mm(h, W2)+B2)
print(y)


tensor([[0.1900]])


## Functions Used

`a = torch.randn((r,c))`: generates a random matrix with dims: rxc.

`b = torch.randn_like(a)`: generates a tensor b with the same shape as that of a.

`torch.sum(a * b)` : used for taking the sums.

`a.shape()`: used for viewing the shape of tensors.

`torch.mm(a,b)`: matrix multiplication

`b = torch.from_numpy(a)`: get a tensor from a numpy array

`b.numpy()`: tensor into a numpy array | **Memory is shared between the numpy array: 'a' and the tensor: 'b'**

##### Changing the shape of the tensors
* `a.reshape(x,y)`: creates a tensor and always copies memory of the source tensor.
* `a.resize_(x,y)`: resizes the tensor and never copies memoyy | "_": in_place operation: not touching the data.(sometimes data is lost if the shape has more/ less elements than the initial tensor )
* `a.view(x,y)`: view never copies memory ever.